name: daiyosei
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - expat=2.7.3=h885b0b7_4
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.0.18=h543e019_0
  - pip=25.3=pyhc872135_0
  - python=3.11.14=h981015d_0
  - setuptools=80.9.0=py311haa95532_0
  - sqlite=3.51.0=hda9a48d_0
  - tk=8.6.15=hf199647_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py311haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - aiocqhttp==1.4.4
      - aiofiles==25.1.0
      - aiosqlite==0.22.0
      - annotated-types==0.7.0
      - anyio==4.12.0
      - blinker==1.9.0
      - cachetools==6.2.4
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.3.1
      - colorama==0.4.6
      - distro==1.9.0
      - dotenv==0.9.9
      - flask==3.1.2
      - google-ai-generativelanguage==0.6.15
      - google-api-core==2.28.1
      - google-api-python-client==2.187.0
      - google-auth==2.45.0
      - google-auth-httplib2==0.3.0
      - google-genai==1.56.0
      - google-generativeai==0.8.6
      - googleapis-common-protos==1.72.0
      - greenlet==3.3.0
      - grpcio==1.76.0
      - grpcio-status==1.71.2
      - h11==0.16.0
      - h2==4.3.0
      - hpack==4.1.0
      - httpcore==1.0.9
      - httplib2==0.31.0
      - httpx==0.28.1
      - hypercorn==0.18.0
      - hyperframe==6.1.0
      - idna==3.11
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - jiter==0.12.0
      - markupsafe==3.0.3
      - openai==2.13.0
      - pillow==12.0.0
      - playwright==1.57.0
      - priority==2.0.0
      - proto-plus==1.27.0
      - protobuf==5.29.5
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pyee==13.0.0
      - pyparsing==3.2.5
      - python-dotenv==1.2.1
      - quart==0.20.0
      - requests==2.32.5
      - rsa==4.9.1
      - sniffio==1.3.1
      - tenacity==9.1.2
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - uritemplate==4.2.0
      - urllib3==2.6.2
      - websockets==15.0.1
      - werkzeug==3.1.4
      - wsproto==1.3.2
prefix: E:\miniconda3\envs\daiyosei
